=== pypi-data/pypi-mirror-368/packages/irie/irie-0.0.60-py3-none-any.whl/irie/apps/prediction/runners/opensees/schemas/hwd_analysis.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Analysis",
  "type": "object",
  "properties": {
    "dynamic_on": {
      "type": "boolean",
      "default": true,
      "description": "turn the dynamic analysis on (true) or off (false)"
    },
    "dynamic_truncated": {
      "type": "boolean",
      "default": false,
      "description": "truncate the dynamic analysis to the first t timesteps"
    },
    "dynamic_timesteps": {
      "type": "integer",
      "default": 500,
      "description": "the t timesteps to which the the dynamic analysis is truncated"
    },
    "input_location": {
      "type": "string",
      "default": "401",
      "description": "locations (node numbers) corresponding to ground motion input, separated by comma, no space. 0 for multiple support excitation."
    },
      "dynamic_integrator": {
      "type": "string",
      "default": "Newmark",
      "description": "numerical integration method"
    },
    "damping_type": {
      "type": "string",
      "enum": ["rayleigh", "modal"],
      "default": "rayleigh",
      "description": "damping strategy"
    },
    "damping_modes": {
      "type": "string",
      "default": "1,2",
      "description": "modes for which to specify damping ratios, separated by comma, no space"
    },
    "damping_ratios": {
      "type": "string",
      "default": "0.015,0.015",
      "description": "damping ratios for selected modes, separated by comma, no space"
    },
    "rayleigh_zerolength_on":{
      "type": "boolean",
      "default": true,
      "description": "turn rayleigh damping on for zerolength elements (abutment, hinge, and column pin springs)"
    },
    "dynamic_scale_factor": {
      "type": "number",
      "default": 1.0,
      "description": "scale factor applied to input ground motion"
    },
    "record_zip": {
      "type": "string",
      "default": "Records/58658_003_20210628_18.29.26.P_SanLo.zip",
      "description": "path to zip file containing the recorded motions for ground motion input and sensor comparison"
    }
  },
  "required": [
    "dynamic_on",
    "dynamic_truncated",
    "input_location",
    "dynamic_integrator",
    "damping_type",
    "damping_modes",
    "damping_ratios",
    "rayleigh_zerolength_on",
    "dynamic_scale_factor",
    "record_zip"
  ]
}

=== pypi-data/pypi-mirror-368/packages/irie/irie-0.0.60-py3-none-any.whl/irie/apps/prediction/runners/opensees/schemas/hwd_analysis_default.json
{
    "$schema": "./hwd_analysis.schema.json",
    "dynamic_on": true,
    "dynamic_truncated": false,
    "dynamic_timesteps": 500,
    "input_location": "401",
    "dynamic_integrator": "Newmark",
    "damping_type": "rayleigh",
    "damping_modes": "1,2",
    "damping_ratios": "0.015,0.015",
    "rayleigh_zerolength_on": true,
    "dynamic_scale_factor": 1.0,
    "record_zip": "Records/58658_003_20210628_18.29.26.P_SanLo.zip"
}
