=== pypi-data/pypi-mirror-368/packages/irie/irie-0.0.60-py3-none-any.whl/irie/apps/prediction/runners/opensees/schemas/hwd_conf.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "Model",
  "properties": {
    "transformation": {
      "type": "string",
      "enum": ["Linear", "PDelta"],
      "default": "Linear",
      "description": "geometric transformation linearity for element deformations"
    },
    "column_linearity": {
      "title": "Column Model",
      "type": "string",
      "enum": ["elastic", "nonlinear"],
      "default": "elastic",
      "description": "column element material linearity"
    },
    "column_pins": {
      "title": "Column Pins",
      "type": "string",
      "enum": ["1", "2", "3", "4", "5"],
      "default": "3",
      "options": {
          "enum_titles": [
            "All rigid",
            "All pinned",
            "Mixed rigid/pinned",
            "All zerolength fiber sections",
            "All integration point fiber sections"
          ]
      },
      "description": "column pin model"
    },
    "column_capbeam_joint":{
      "type": "string",
      "enum": ["none", "rigidlink", "jointoffset"],
      "default": "none",
      "description": "offsets between tops of columns and column-cap beam joints"
    },
    "abutment_model": {
      "type": "string",
      "enum": ["none", "linear", "simplified", "complex"],
      "default": "linear",
      "description": "abutment model"
    },
    "hinge_model": {
      "type": "string",
      "enum": ["none", "linear", "simplified", "complex"],
      "default": "linear",
      "description": "in-span hinge model"
    },
    "Ec": {
      "type": "number",
      "default": 3530.5,
      "description": "concrete modulus of elasticity (ksi)"
    },
    "Ecol": {
      "type": "number",
      "default": 3530.5,
      "description": "column concrete modulus of elasticity (ksi)"
    },
    "Es": {
      "type": "number",
      "default": 29000.0,
      "description": "steel tensile modulus of elasticity (initial elastic tangent, ksi)"
    },
    "CGa": {
      "type": "number",
      "default": 50.0,
      "description": "abutment shear stiffness coefficient"
    },
    "CGh": {
      "type": "number",
      "default": 60.0,
      "description": "in-span hinge shear stiffness coefficient"
    }
  },
  "required": [
    "transformation",
    "column_linearity",
    "column_pins",
    "column_capbeam_joint",
    "abutment_model",
    "hinge_model",
    "Ec",
    "Ecol",
    "Es",
    "CGa",
    "CGh"
  ]
}

=== pypi-data/pypi-mirror-368/packages/irie/irie-0.0.60.tar.gz/irie-0.0.60/src/irie/apps/prediction/runners/opensees/schemas/hwd_conf_default.json
{
    "$schema": "./hwd_conf.schema.json",
    "transformation": "Linear",
    "column_linearity": "elastic",
    "column_pins": "3",
    "column_capbeam_joint": "none",
    "abutment_model": "linear",
    "hinge_model": "linear",
    "Ec": 3530.5,
    "Ecol": 3530.5,
    "Es": 29000.0,
    "CGa": 50.0,
    "CGh": 60.0
}
